#!/bin/bash

#
# removes all local branches already merged to master
#

if !(git is-repo); then
    echo "No git repo."
    exit 1
fi

merged=($(git branch --merged master | grep -v "\* master"))
for branch in "${merged[@]}"
do
    git branch -d "${branch}"
done
exit 0
