#!/bin/bash

#
# prints one line of useful information about the state of the git repository in the current working directory (if any)
# to be added to ones PS1
#

merged=($(git branch --merged master | grep -v "\* master"))

function git_status {
    if [[ $(git status &>/dev/null) -eq 0 ]]; then
        local branch
        if branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null); then
            if [[ "$branch" == "HEAD" ]]; then
                branch='detached*'
            fi
            git_branch="git::$branch"
        else
            git_branch=""
        fi

        local status=$(git status --porcelain 2> /dev/null)
        if [[ "$status" != "" ]]; then
            git_dirty="*"
        else
            git_dirty=""
        fi

        local git_stashed_changes=$(git stash list | wc -l)

        local git_commits_ahead=$(git rev-list @{u}.. --count)
        local git_commits_behind=$(git rev-list ..@{u} --count)

        echo -en "${git_branch}${git_dirty} "
        if [ ${git_commits_ahead} -gt 0 ]; then
            echo -en "↗${git_commits_ahead} "
        fi
        if [ ${git_commits_behind} -gt 0 ]; then
            echo -en "↘${git_commits_behind} "
        fi
        if [ ${git_stashed_changes} -gt 0 ]; then
            echo -en "⇣${git_stashed_changes}"
        fi
    fi
}

echo -n "$(git_status)"