#!/usr/bin/env bash

function _mvn-switch-settings {
    local cur prev options
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    
    files=($(find $HOME/.m2/ -type f -name "settings_*.xml"))
    options=""
    for file in "${files[@]}"
    do
        option="${file}"
        option="${option##*/settings_}"
        option="${option%%.xml}"
        options+="${option} "
    done

    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _mvn-switch-settings mvn-switch-settings
